export const FETCH_MATCH_DETAILS_REQUEST = 'FETCH_MATCH_DETAILS_REQUEST'
export const FETCH_MATCH_DETAILS_SUCCESS = 'FETCH_MATCH_DETAILS_SUCCESS'
export const FETCH_MATCH_DETAILS_FAILURE = 'FETCH_MATCH_DETAILS_FAILURE'